config/routes.rb
MobileController::Application.routes.draw do
  mount RedactorRails::Engine => 'redactor_rails'

  scope :admin do
    devise_for :admin,
               path: '',
               path_names: {
                   sign_in: 'login',
                   sign_out: 'logout'
               },
               controllers: {
                   sessions: 'auth/sessions'
               },
               class_name: 'User::Admin'
  end

  namespace :admin do
    authenticated :admin do
      root to: 'welcome#index'

      resources :clients do
        member do
          get :projects
        end
      end

      resources :tasks do
        resources :steps, only: [:new, :create] do
          post :sort, on: :collection
        end

        resources :fields, except: :all do
          resources :variants do
            post :sort, on: :collection
          end
        end
      end

      resources :steps do
        resources :blocks, only: [:new, :create] do
          post :sort, on: :collection
        end
      end

      resources :blocks do
        resources :fields, only: [:new, :create] do
          post :sort, on: :collection
        end
      end

      resources :fields do
        resources :options, only: [:new, :create] do
          post :sort, on: :collection
        end
      end

      resources :operators, :audits, :admins, :task_types, except: [:show]

      resources :projects, except: [:show] do
        resources :targets, except: [:show] do
          get :batch, on: :collection
          post :batch, on: :collection, action: :batch_update
        end

        resources :tasks, only: [:index, :new, :create]
      end
    end

    unauthenticated :admin do
      root to: redirect('admin/login'), as: :noauth
      match '*not_found', to: redirect('admin/login'), via: :all
    end
  end

  scope :client do
    devise_for :client,
               path: '',
               path_names: {
                   sign_in: 'login',
                   sign_out: 'logout'
               },
               controllers: {
                   sessions: 'auth/sessions'
               },
               class_name: 'User::Client'
  end

  namespace :client do
    authenticated :client do
      root to: redirect('client/projects')
      resources :projects, only: [:index, :show]
      resources :archives, path: :archive, only: [:index]
      resources :comings, path: :coming, only: [:index]
      resources :feedbacks, path: :feedback, except: [:edit, :update] do
        resources :messages, only: [:create, :destroy]
      end

    end

    unauthenticated :client do
      root to: redirect('client/login'), as: :noauth
      match '*not_found', to: redirect('client/login'), via: :all
    end
  end

  scope :operator do
    devise_for :operator,
               path: '',
               path_names: {
                   sign_in: 'login',
                   sign_out: 'logout'
               },
               controllers: {
                   sessions: 'auth/sessions'
               },
               class_name: 'User::Operator'
  end

  namespace :operator do
    authenticated :operator do
      root to: 'welcome#index'

      resources :tasks, only: [:index, :show, :update]
      resources :feedbacks, path: :feedback, only: [:index, :show] do
        patch '', action: :accept, on: :member
        resources :messages, only: [:create, :destroy]
      end
    end

    unauthenticated :operator do
      root to: redirect('operator/login'), as: :noauth
      match '*not_found', to: redirect('operator/login'), via: :all
    end
  end

  scope :agent do
    devise_for :agent,
               path: 'profile',
               skip: :all,
               class_name: 'User::Audit'
  end

  namespace :api do

    root to: 'welcome#index'
    post :user, to: 'user#login'

    #authenticated :agent do
      delete :user, to: 'user#logout'
      #post :missions, to: 'missions#empty'

      post :sync, to: 'sync#sync'
      post :upload, to: 'upload#recieve'

      resources :missions, only: [:update]

      resources :user_tasks, path: :tasks, only: [:destroy, :update]
      resource :geolocation
      resource :map
    #end

    #unauthenticated :agent do
    #  root to: redirect('agent/profile/login'), as: :noauth
    #  match '*not_found', to: redirect('agent/profile/login'), via: :all
    #end
  end


  namespace :agent do
    root to: 'welcome#index'


    # registration and confirmation
    authenticated :agent do
      get 'dashboard', to: 'dashboard#show'

      resources :user_tasks, path: :tasks
      resources :feedbacks, path: :feedback, except: [:edit, :update] do
        resources :messages, only: [:create, :destroy]
      end

      resource :profile, except: :all, controller: :profile, as: :profile do
        get :edit, action: :edit, on: :member
        post :edit, to: :update
      end

      get :logout, as: :logout, to: 'profile#logout'
    end

    scope :profile, controller: :profile do
      get :login
      post :login, action: :do_login

      get :recover
      post :recover, action: :do_recover

      get :confirm
      post :confirm, action: :do_confirm

      get :change
      post :change, action: :do_change

      get :register
      post :register, action: :do_register
    end
  end

#unauthenticated do
#  root to: redirect('login'), as: :noauth
#  match '*not_found', to: redirect('login'), via: :all
#end

  root to: 'welcome#index'
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :client, class_name: 'User::Client', foreign_key: :client_id
  validates :name, :client, presence: true

  has_many :targets
  has_many :tasks

  scope :active, -> { where('start_date <= ? and end_date >= ?', Time.now.to_date, Time.now.to_date) }
  scope :archive, -> { where('end_date < ?', Time.now.to_date) }
  scope :coming, -> { where('start_date > ?', Time.now.to_date) }

  def build_project_task(params={})
    @task = Task.new(params)
    @task.project = self
    @task
  end

  def completed_for
    (tasks.sum(&:completed_for)/tasks.size.to_f * 100).to_i
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::BaseController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :tasks]

  # GET /admin/projects
  # GET /admin/projects.json
  def index
    @projects = Project.all
  end

  # GET /admin/projects/1
  # GET /admin/projects/1.json
  def show
  end

  # GET /admin/projects/new
  def new
    @project = Project.new
  end

  # GET /admin/projects/1/edit
  def edit
  end

  def tasks
    @tasks = @project.tasks
  end

  # POST /admin/projects
  # POST /admin/projects.json
  def create
    @project = Project.new(admin_project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to admin_projects_path, notice: 'Проект создан успешно' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/projects/1
  # PATCH/PUT /admin/projects/1.json
  def update
    respond_to do |format|
      if @project.update(admin_project_params)
        format.html { redirect_to admin_projects_path, notice: 'Проект сохранен успешно' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/projects/1
  # DELETE /admin/projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to admin_projects_url, notice: 'Проект удален успешно' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def admin_project_params
    #TODO safe params
    params.require(:project).permit!
  end
end

app/controllers/client/projects_controller.rb
class Client::ProjectsController < Client::BaseController
  before_action :set_project, only: [:show]

  def show
  end

  def index
    @projects = current_client.projects
  end

  private
  def set_project
    @project = current_client.projects.find(params[:id])
  end
end

app/views/admin/projects/_form.html.erb
<%= render 'tabs', selected: 'main' %>

<%= simple_form_for [:admin, @project], url: @project.new_record? ? admin_projects_path : admin_project_path(@project) do |f| %>
    <%= simple_fields_for 'project', @project do |f| %>
        <%= f.error_notification %>

        <div class="form-inputs">

          <%= f.input :name %>
          <%= f.input :description %>
          <hr />
          <%= f.association :client, selected: params[:client] %>
          <hr />
          <%= f.input :start_date, as: :date_picker %>
          <%= f.input :end_date, as: :date_picker %>
          <hr />
        </div>

        <div class="form-group">
          <div class="col-sm-12 col-sm-offset-2">
            <%= f.button :submit, save_or_update(@project), class: 'btn-primary' %>
            <%= link_to 'Отмена', admin_projects_path, class: 'btn btn-default' %>
          </div>
        </div>
    <% end %>
<% end %>

app/views/admin/projects/_list.html.erb
<table class="table table-hover">
  <thead>
  <tr>
    <th>Проект</th>
    <th class="text-center">Точки</th>
    <th class="text-center">Задачи</th>

    <th></th>
  </tr>
  </thead>

  <tbody>
  <% projects.each do |project| %>
      <tr>
        <td>
          <%= project.name %>

          <%= content_tag :div, class: 'text-muted' do %>
              <%= Russian::l(project.start_date, format: :short) %>
              — <%= Russian::l(project.end_date, format: :short) %>
          <% end %>

          <%= content_tag :div, class: 'text-muted' do %>
              Клиент: <%= project.client %>
          <% end %>
        </td>

        <td class="text-center">
          <%= link_to project.targets.size, admin_project_targets_path(project) %>
        </td>

        <td class="text-center">
          <%= link_to project.tasks.size, admin_project_tasks_path(project) %>
        </td>

        <td>
          <div class="pull-right">
            <div class="btn-group">
              <%= link_to pencil_icon,
                          edit_admin_project_path(project), :class => 'btn btn-xs btn-default' %>

              <%= link_to trash_icon,
                          admin_project_path(project),
                          :method => :delete,
                          :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))},
                          :class => 'btn btn-xs btn-danger' %>
            </div>
          </div>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/projects/_tabs.html.erb
<ul class="nav nav-tabs">
  <%= content_tag :li, class: (:active if selected == 'main') do %>
      <% if selected == 'main' and @project.new_record? %>
          <a href="#">
            Основное
          </a>
      <% else %>
          <a href="<%= edit_admin_project_path(@project) %>">
            Основное
          </a>
      <% end %>
  <% end %>

  <% unless @project.new_record? %>
      <%= content_tag :li, class: (:active if selected == 'targets') do %>
          <a href="<%= admin_project_targets_path(@project) %>">Точки</a>
      <% end %>
  <% end %>

  <% unless @project.new_record? %>
      <%= content_tag :li, class: (:active if selected == 'tasks') do %>
          <a href="<%= admin_project_tasks_path(@project) %>">Задачи</a>
      <% end %>
  <% end %>
</ul>

app/views/admin/projects/edit.html.erb
<div class="page-header">
  <h1>Правка проекта: <%= @project.name %></h1>
</div>

<%= render 'form' %>

app/views/admin/projects/index.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to plus_icon('Проект'), new_admin_project_path, class: 'btn btn-default' %>
  </div>
  <h1>Проекты</h1>
</div>

<%= render 'list', projects: @projects %>

app/views/admin/projects/new.html.erb
<div class="page-header">
  <h1>Добавление проекта</h1>
</div>

<%= render 'form' %>