config/routes.rb
MobileController::Application.routes.draw do
  mount RedactorRails::Engine => 'redactor_rails'

  scope :admin do
    devise_for :admin,
               path: '',
               path_names: {
                   sign_in: 'login',
                   sign_out: 'logout'
               },
               controllers: {
                   sessions: 'auth/sessions'
               },
               class_name: 'User::Admin'
  end

  namespace :admin do
    authenticated :admin do
      root to: 'welcome#index'

      resources :clients do
        member do
          get :projects
        end
      end

      resources :tasks do
        resources :steps, only: [:new, :create] do
          post :sort, on: :collection
        end

        resources :fields, except: :all do
          resources :variants do
            post :sort, on: :collection
          end
        end
      end

      resources :steps do
        resources :blocks, only: [:new, :create] do
          post :sort, on: :collection
        end
      end

      resources :blocks do
        resources :fields, only: [:new, :create] do
          post :sort, on: :collection
        end
      end

      resources :fields do
        resources :options, only: [:new, :create] do
          post :sort, on: :collection
        end
      end

      resources :operators, :audits, :admins, :task_types, except: [:show]

      resources :projects, except: [:show] do
        resources :targets, except: [:show] do
          get :batch, on: :collection
          post :batch, on: :collection, action: :batch_update
        end

        resources :tasks, only: [:index, :new, :create]
      end
    end

    unauthenticated :admin do
      root to: redirect('admin/login'), as: :noauth
      match '*not_found', to: redirect('admin/login'), via: :all
    end
  end

  scope :client do
    devise_for :client,
               path: '',
               path_names: {
                   sign_in: 'login',
                   sign_out: 'logout'
               },
               controllers: {
                   sessions: 'auth/sessions'
               },
               class_name: 'User::Client'
  end

  namespace :client do
    authenticated :client do
      root to: redirect('client/projects')
      resources :projects, only: [:index, :show]
      resources :archives, path: :archive, only: [:index]
      resources :comings, path: :coming, only: [:index]
      resources :feedbacks, path: :feedback, except: [:edit, :update] do
        resources :messages, only: [:create, :destroy]
      end

    end

    unauthenticated :client do
      root to: redirect('client/login'), as: :noauth
      match '*not_found', to: redirect('client/login'), via: :all
    end
  end

  scope :operator do
    devise_for :operator,
               path: '',
               path_names: {
                   sign_in: 'login',
                   sign_out: 'logout'
               },
               controllers: {
                   sessions: 'auth/sessions'
               },
               class_name: 'User::Operator'
  end

  namespace :operator do
    authenticated :operator do
      root to: 'welcome#index'

      resources :tasks, only: [:index, :show, :update]
      resources :feedbacks, path: :feedback, only: [:index, :show] do
        patch '', action: :accept, on: :member
        resources :messages, only: [:create, :destroy]
      end
    end

    unauthenticated :operator do
      root to: redirect('operator/login'), as: :noauth
      match '*not_found', to: redirect('operator/login'), via: :all
    end
  end

  scope :agent do
    devise_for :agent,
               path: 'profile',
               skip: :all,
               class_name: 'User::Audit'
  end

  namespace :api do

    root to: 'welcome#index'
    post :user, to: 'user#login'

    #authenticated :agent do
      delete :user, to: 'user#logout'
      #post :missions, to: 'missions#empty'

      post :sync, to: 'sync#sync'
      post :upload, to: 'upload#recieve'

      resources :missions, only: [:update]

      resources :user_tasks, path: :tasks, only: [:destroy, :update]
      resource :geolocation
      resource :map
    #end

    #unauthenticated :agent do
    #  root to: redirect('agent/profile/login'), as: :noauth
    #  match '*not_found', to: redirect('agent/profile/login'), via: :all
    #end
  end


  namespace :agent do
    root to: 'welcome#index'


    # registration and confirmation
    authenticated :agent do
      get 'dashboard', to: 'dashboard#show'

      resources :user_tasks, path: :tasks
      resources :feedbacks, path: :feedback, except: [:edit, :update] do
        resources :messages, only: [:create, :destroy]
      end

      resource :profile, except: :all, controller: :profile, as: :profile do
        get :edit, action: :edit, on: :member
        post :edit, to: :update
      end

      get :logout, as: :logout, to: 'profile#logout'
    end

    scope :profile, controller: :profile do
      get :login
      post :login, action: :do_login

      get :recover
      post :recover, action: :do_recover

      get :confirm
      post :confirm, action: :do_confirm

      get :change
      post :change, action: :do_change

      get :register
      post :register, action: :do_register
    end
  end

#unauthenticated do
#  root to: redirect('login'), as: :noauth
#  match '*not_found', to: redirect('login'), via: :all
#end

  root to: 'welcome#index'
end

app/views/admin/admins/_form.html.erb
<%= simple_form_for [:admin, @user], url: @user.new_record? ? admin_admins_path : admin_admin_path(@user), html: {multipart: true} do |f| %>
    <%= simple_fields_for 'user', @user do |f| %>
        <%= f.error_notification %>

        <div class="form-inputs">
          <%# TODO phone input mask %>
          <%= f.input :login %>
          <%= f.input :password %>

          <hr/>

          <%= f.simple_fields_for 'profile', @user.profile do |p| %>
              <%= p.input :email %>
              <%= p.input :first_name %>
              <%= p.input :last_name %>
              <hr/>
          <% end %>

        </div>

        <div class="form-group">
          <div class="col-sm-12 col-sm-offset-2">
            <%= f.button :submit, save_or_update(@user), class: 'btn-primary' %>
            <%= link_to 'Отмена', admin_admins_path, class: 'btn btn-default' %>
          </div>
        </div>
    <% end %>
<% end %>

app/views/admin/admins/edit.html.erb
<div class="page-header">
  <h1>Правка Админа</h1>
</div>

<%= render 'form' %>

app/views/admin/admins/index.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to plus_icon('Администратор'), new_admin_admin_path, class: 'btn btn-default' %>
  </div>
  <h1>Администраторы</h1>
</div>

<table class="table table-hover">
  <thead>
  <tr>
    <th>Админ</th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td>
            <%= user.full_name %>
        </td>

        <td>
          <div class="pull-right">
              <div class="btn-group">
                <%= link_to pencil_icon,
                            edit_admin_admin_path(user), :class => 'btn btn-xs btn-default' %>

                <%= link_to trash_icon,
                            admin_admin_path(user),
                            :method => :delete,
                            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                            :class => 'btn btn-xs btn-danger' %>
              </div>
          </div>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/admins/new.html.erb
<div class="page-header">
  <h1>Добавление админа</h1>
</div>

<%= render 'form' %>